### PR TITLE
Modified Using statements with conditional compiler directive. 

### PR DESCRIPTION
**Pull request by mrlucmorin**
Only C# scripts done for now.

### CODE REVIEW

**Comment by Suplanus** [comment]
Not needed in the current EPLAN versions

**Comment by mrlucmorin** [comment]
I've been asking about this, and the EPLAN answer was more than vague.

What has changed exactly? Do you have the details?

**Comment by Suplanus** [comment]
I saw that the errors in the system messages were removed.
Also the additional error if you have an error in compile time.

So i dont use this any more since 2.3 i think.

**Comment by mrlucmorin** [comment]
Interesting. Did you know that VB.NET is still giving error messages? Actually, the way namespaces are handled between C# and VB.NET is different, and I was unable to get a definitive answer about this.

Please check  my VB.NET scripting environment project on GitHub:

https://github.com/mrlucmorin/EPLAN-Scripting-for-VB.NET

Maybe we can also get rid of the #If section? If you have some ideas, I will be more than happy to listen :-)

Cheers

**Comment by Suplanus** [comment]
I saw the project of you on GitHub.

Dont know thats a problem in VB.NET. I will look into it.

**Pull request closed without merging**
